spring:
  application:
    name: catalog-api
  datasource:
    url: ${DB_URL1:jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:5432/postgres?sslmode=require}
    username: ${DB_USERNAME1:postgres.aksxbcingfgvaffrrnag}
    password: ${DB_PASSWORD1:ilanfoods@123}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: ${DB_POOL_MAX:5}
      minimum-idle: ${DB_POOL_MIN:1}
      idle-timeout: ${DB_IDLE_TIMEOUT_MS:60000}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  flyway:
    enabled: false
  mail:
    host: localhost
    port: 25
    username:
    password:
    properties:
      mail.smtp.auth: false
      mail.smtp.starttls.enable: true

server:
  port: ${PORT:8080}
  servlet:
    context-path: /catalog

logging:
  level:
    org.springframework: info

supabase:
  project-reference: ${SUPABASE_PROJECT:aksxbcingfgvaffrrnag}
  jwt:
    secret: ${SUPABASE_JWT_SECRET:Ifh0Xf7sNQwg4YaF5+BuVph/+n9hAyLPOALZoERKGoPNCw82PDeCOZNW+BhVY76ALpnw9wgWO3YnTz20ZUfzKA==}
  s3:
    access-key-id: ${SUPABASE_ACCESS_KEY_ID:ecda7550a746a6efded3e4ab5ccab8a8}
    secret-access-key: ${SUPABASE_SECRET_ACCESS_KEY:6bfef46403a165c138bd54e2a18172a0c12e17fa1267423a14ded99005d0f7c8}
    region: ${SUPABASE_REGION:us-east-1}
    endpoint-url: ${SUPABASE_ENDPOINT_URL:https://aksxbcingfgvaffrrnag.storage.supabase.co/storage/v1/s3}
    bucket-name: ${SUPABASE_BUCKET:products}

--- # Postgres profile example

logging:
  level:
    org.springframework: info
